services:
  - type: web
    name: seattlejoy
    repo: https://github.com/michaelcolenso/seattlejoy
    runtime: node
    plan: free
    branch: master
    buildCommand: npm ci && npm run build
    startCommand: npm start
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
